import os
import sys

from kevinbotlib.logger import Logger

import kevinbotv3.tools.cli

try:
    import pathenv
except NotImplementedError:
    pathenv = None


def install():
    if not pathenv:
        Logger().error("Your shell is not supported by pathenv. Skipping autoinstall.")
        return

    # Generate a bash script
    script = f"""#! /bin/bash
# This script was auto-generated by Kevinbot v3
{sys.executable} {os.path.dirname(kevinbotv3.tools.cli.__file__)}/cli.py "$@"
"""
    if not os.path.exists(os.path.expanduser("~/tools")):
        os.makedirs(os.path.expanduser("~/tools"))
        Logger().info("Created ~/tools directory")

    if not os.path.exists(os.path.expanduser("~/tools/kevinbotv3")):
        with open(os.path.expanduser("~/tools/kevinbotv3"), "w") as f:
            f.write(script)
        Logger().info("Created ~/tools/kevinbotv3")

        os.chmod(os.path.expanduser("~/tools/kevinbotv3"), 0o755)  # noqa: S103
        Logger().info("Set permissions on ~/tools/kevinbotv3 to 755")

    try:
        if os.path.expanduser("~/tools") not in os.environ["PATH"].split(os.pathsep):
            pathenv.add_to_path(os.path.expanduser("~/tools"))
            Logger().info("Added ~/tools to PATH")
    except NotImplementedError as e:
        Logger().warning(f"Failed to add ~/tools to PATH: {e!r}")
